name: build

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: windows-2022

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Set up MSBuild
        uses: microsoft/setup-msbuild@v2

      - name: Build ReShade (32-bit)
        run: |
          msbuild ReShade.sln /p:Configuration=Release /p:Platform=32-bit

      - name: Build ReShade (64-bit)
        run: |
          msbuild ReShade.sln /p:Configuration=Release /p:Platform=64-bit

      - name: Build ReShade Setup
        run: |
          msbuild ReShade.sln /p:Configuration="Release Setup"

      - name: Upload ReShade Setup
        uses: actions/upload-artifact@v4
        with:
          name: ReShade Setup
          path: './bin/AnyCPU/Release/ReShade Setup.exe'
